### ISSUE TITLE
TYPO

### ISSUE THREAD

**Issue by Davinci360** [learn-co-curriculum/phase-0-intro-to-js-2-modifying-objects#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.
https://github.com/learn-co-curriculum/phase-0-intro-to-js-2-modifying-objects
## What should be changed?
Update an Object nondestructively using the spread operator
Using Object.assign()
Update an Object nondestructively using Object.assign()
> Suggest your change here. Let us know what section or line of the Readme needs
Condense to one list item and eliminate redundant Object.assign()
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.

## Additional context

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Thanks @Davinci360 ! This fix has been made. It may not be updated in your Canvas course but you can see the change here on GitHub.

Thanks for contributing to the Flatiron School curriculum 💙
