### ISSUE TITLE
a

### ISSUE THREAD

**Issue by isayyaa93** [learn-co-curriculum/phase-0-intro-to-js-2-modifying-objects#5]
<img width="1225" alt="Screenshot 2022-02-23 at 10 39 13 PM" src="https://user-images.githubusercontent.com/70542765/155453642-dc09cb07-b231-49a4-ab6b-2109ae75196c.png">

**Comment by lizbur10** [comment]
Hi @isayyaa93 ! It looks like you may have gotten this working so I'm going to go ahead and close this issue. If there's still a problem, please feel free to reopen it 💙
