### ISSUE TITLE
Typo in Modifying objects

### ISSUE THREAD

**Issue by ahmadalashtar** [learn-co-curriculum/phase-0-intro-to-js-2-modifying-objects#7]
### Canvas Link

https://my.learn.co/courses/695/pages/modifying-objects?module_item_id=85935

### Concern

 Like the spread operator, Object.assign allow us to

### Suggested Changes

 Like the spread operator, Object.assign allows us to

**Comment by lizbur10** [comment]
Hi @ahmadalashtar ! Thank you for bringing this our attention - it has now been fixed 💙
